### ISSUE TITLE
How to show tooltip without tapping?

### ISSUE THREAD

**Issue by olezhko** [EmilAlipiev/myToolTip#1]
How to show tooltip without tapping? for example, when OnAppearing page

**Comment by EmilAlipiev** [comment]
Hi, sorry for the late reply.  I was thinking about this feature as well.  it will be nice to have that feature to show tooltips when user uses the app first time. thats why i already started a new [branch ](https://github.com/EmilAlipiev/myToolTip/tree/IsOpenProperty)

Android is working already fine as you can see in the gif below

![tooltip](https://user-images.githubusercontent.com/10422347/90957053-c54d8380-e48b-11ea-9330-ef4d02353aaa.gif)

Ios should be also working same way i believe. I havent tested yet.

But Uwp has a problem on closing the popup. It is displaying fine on OnAppearing but I couldnt find out how to close it. 
There is a property called IsOpen, when you set this It shows the popup programmatically but which event is to set IsOpen false is tricky. I tried Tapped and LostFocused events but somehow they aren't fired. If you may give it a try and figure out, you may send me a PR and i will push a new version.

**Comment by olezhko** [comment]
Good. I tested in my application. Thank you!
